<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>user register positive cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bfad8bdf-6369-4b57-8683-b4ef0e9c4047</testSuiteGuid>
   <testCaseLink>
      <guid>b45b3d33-9d28-45a7-801b-728e563531ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/positive test cases/TC05-as a user i can go to login page if already have account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a19670f-0b8f-4f0e-84e1-a6c1b5766790</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cbd953a-b02d-44c5-9743-366cb1d4e5aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67c737af-7819-4c71-8811-8ab2745d46ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d1fc3fa-eb76-41d8-949d-db989cf8dfa5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/positive test cases/TC02-as a user i can register with apple id</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b592edcb-35ea-4e95-a0ff-9231bf8c869b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62083bd4-ee50-4d4c-bc25-d450cf0b1cd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b33ae6dd-26c3-49f3-9f7b-1287bf580f19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abde58e7-b0b5-445f-8204-b5b0d6feeb68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/positive test cases/TC04-as a user i can register with facebook</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59e29ca5-472a-4d13-b33d-f2d352e7c18e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ba16e85-b9e3-46c3-afe2-0b53c1a0fd2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8209cbf4-5116-4f0f-90c3-bf0a4921e0ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ccce22f-aef5-4824-9178-a8cd4a7b688a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/positive test cases/TC03-as a user i can register with google</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05309b21-330d-48ef-93ef-ea94dae40384</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a71d5111-0ec7-47e1-a851-1ff37313eef1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00fdbd68-be27-4d1e-84ac-466c9a34825b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a6862ab-6137-4e72-8059-19fcb9d3aad1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/positive test cases/TC06-as a user i can go to terms and condition page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa9d0cbe-c2e3-4ca7-afc3-bc8339930d37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afdce26a-a5fc-4e87-b676-cc7f9b695e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c004706b-e1ac-4f34-87a9-c14472368bde</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dbd9a7f6-9b53-4436-b844-43545f8be544</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/positive test cases/TC01-as a user i can register with valid email and name</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a442a697-c809-4766-9536-9450b73ebf3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3abee2e1-e1f5-4c23-964f-f70f604cb13c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90593472-3f0f-473e-9854-4c3d1b65d783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbd27288-2da6-4cef-b79e-6202f3fbe457</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d88447a-2e8d-4367-9f36-4943725d03d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/positive test cases/TC06-as a user i can go to terms and condition page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa9d0cbe-c2e3-4ca7-afc3-bc8339930d37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afdce26a-a5fc-4e87-b676-cc7f9b695e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c004706b-e1ac-4f34-87a9-c14472368bde</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c36dcf5-fd80-49ff-8f81-af45cea83a85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/positive test cases/TC07-as a user i can edit my email before click register</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74edab18-9341-45ed-8cfb-f8a6933c979f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b4bf4f9-4054-45c4-b0de-dddbb392d017</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd415ee9-4dd6-43c1-bd84-ba38db807a03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1c8b5bd-8f42-4a91-99b7-0d79913515c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8ca9d4c-9f50-4bc7-9e76-f29b86b596b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b974bd11-8bcf-4e47-acce-f4011ded1bf6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88bf3d4b-6e2f-4188-904a-5614d9158f7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/positive test cases/TC08-as an existing user i will get pop up option to continue login as existing user</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>605234dc-d3c4-492f-be46-7f412ee8aff9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6eb7b56f-e5b5-4168-ad41-caab59b795b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e7e5cb2-a47c-445d-9ad4-5995132da96f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6df22dc5-e8b9-48b9-a327-7a08a6021af3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
