<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>user register negative test cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c7db643b-9216-48fb-b633-d77d227fe82c</testSuiteGuid>
   <testCaseLink>
      <guid>85f70e38-a467-441d-9a9c-51db4643cdb5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/negative test cases/TC10-as a user i cannot continue register if name is empty</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4278037-f3c9-4b40-8055-b58519d2ad51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd958c62-f192-4c49-8aef-b28f4f9250ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71cb9072-ad44-4202-9f84-d0d94809f450</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91ad24c1-3e5f-40c4-bcf8-8f26c6d29dfa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91c7cdde-e157-4e31-93f0-bdc3721a5a01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/negative test cases/TC13-as a user i cannot register with invalid name format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60c9baf8-fa20-42a4-b2c9-a176ca3fac0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b1dd52c-c5d5-4d04-9d1e-f53ad201cf90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c0ef323-77fc-4053-b978-ed0700a66eb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0126907-4f4f-49db-9492-39ba6c3de99c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eae4ef9d-38b2-4ce4-a207-b7aa2bea498f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c315460-b2e5-4579-a905-3915cd5405db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/negative test cases/TC12-as a user i cannot input name more than 70 char</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d95dd2e3-5afc-4582-a10d-ec6e143d8e22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce905b9c-601e-4965-b079-efcbd7658ddb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3767b838-cd6e-4eb8-a606-2ce06adac68c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a26f172-6483-4a4c-b96f-e86381164146</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd801ce2-da18-4dfd-9638-5372dfd96cf2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d568c32-95b6-4d22-8829-85799440b636</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/negative test cases/TC09-as a user i cannot continue register if email is empty</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fce8c48-8fe8-4e94-8102-b06479eb1ea7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>918c5454-0a3d-4186-bce2-23735eb3fcfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0173458-28e7-474c-8bca-c4a06bd13fc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a865edfd-8c68-49c6-8395-331c21ac96f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f84d97cd-ad77-421c-a294-fc8f8eb58d1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test cases/negative test cases/TC11-as a user i cannot register with invalid email format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20147089-48ff-496e-921e-04396291df15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67ef7bd6-66df-4852-9dcf-ef883198dd86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>242831fc-b3c5-467a-b5f8-d7da18f48ecf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12d16f00-8471-420a-b9c8-fd6dd3310e42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd7652f4-8696-4aa5-ab94-24f33730d8a9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
