<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_back</name>
   <tag></tag>
   <elementGuidId>75d95db5-7b14-478d-bead-015378fc9b5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//header//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//header//button</value>
   </webElementProperties>
</WebElementEntity>
